Feature/css to ts
SimplrJS/css-to-ts pull request #2
Opened 2017-04-10 18:15 UTC by DeividasBakanas

2017-04-10 18:34 UTC, DovydasNavickas requested changes

2017-04-10 18:34 UTC, DovydasNavickas commented on dist/arguments.js
> +    .option("r", {
Remove `-r` because of possible confusion with `--recursive` and similar ones.

2017-04-10 18:34 UTC, DovydasNavickas commented on dist/arguments.js
> +    .option("p", {
Remove `-p` because of possible confusion with `--project` and similar ones.

2017-04-10 18:34 UTC, DovydasNavickas commented on dist/arguments.js
> +    .option("c", {
Remove `-c` because of possible confusion.

2017-04-10 18:34 UTC, DovydasNavickas commented on dist/arguments.js
> +    .options("d", {
Remove `-d` because of possible confusion with `--dist`, `--destination` and similar ones.

2017-04-10 18:34 UTC, DovydasNavickas commented on src/css-to-ts.ts
> +    private formTs(stringifiedCss: string, variableName: string, headerComment?: string) {
`formTs` -> `generateTs`

2017-04-10 18:34 UTC, DovydasNavickas commented on src/main.ts
> +    private handleFile(filePath: string) {
`handle` says nothing. Name should be more specific.

2017-04-10 18:34 UTC, DovydasNavickas commented on src/main.ts
> +    private formVarName(fileName: string) {
`form` -> `generate`

2017-04-10 18:34 UTC, DovydasNavickas commented on src/main.ts
> +    private formFileName(fileName: string, extension?: string) {
`form` -> `generate`

2017-04-10 18:34 UTC, DovydasNavickas commented on src/css-to-ts.ts
> +    private async emitFile(outPath: string, content: string) {
Use `mz-fs` instead of writing your own `async` methods.

2017-04-10 18:34 UTC, DovydasNavickas commented on src/css-to-ts.ts
> +    private async doesDirExist(dirPath: string) {
`doesDirExist` -> `dirExists` naming would be better.
But use `mz/fs` instead.

2017-04-10 18:34 UTC, DovydasNavickas commented on src/css-to-ts.ts
> +            const isDirExist = await this.doesDirExist(this.tsDir);
`isDirExist` -> `dirExists`

2017-04-10 18:58 UTC, GiedriusGrabauskas requested changes

2017-04-10 18:58 UTC, GiedriusGrabauskas commented on package.json
>      "@types/yargs": "^6.6.0",
Move to `dependencies`

2017-04-10 18:58 UTC, GiedriusGrabauskas commented on @types/arguments.d.ts
> +export declare var Arguments: any;
Check for `Arguments` type.

2017-04-10 18:58 UTC, GiedriusGrabauskas commented on src/main.ts
> +    private async run() {
Move all code from `run` method into `constructor`

2017-04-10 18:58 UTC, GiedriusGrabauskas commented on src/main.ts
> +            for (let index in filesArray) {
Maybe use:
```ts
for(let i=0; i<filesArray.length; i++) { 
...
}
```

2017-04-10 18:58 UTC, GiedriusGrabauskas commented on src/main.ts
> +            console.log(error);
Handle some errors.

2017-04-10 18:58 UTC, GiedriusGrabauskas commented on src/main.ts
> +        console.log(error);
Handle some errors

2017-04-10 18:58 UTC, GiedriusGrabauskas commented on src/main.ts
> +    private formFileName(fileName: string, extension?: string) {
`construct` or `generate` file name.

2017-04-10 18:58 UTC, GiedriusGrabauskas commented on src/css-to-ts.ts
> +            console.log(`Reading css from ${tsPath}.`);
`cssPath`?

2017-04-10 18:58 UTC, GiedriusGrabauskas commented on src/css-to-ts.ts
> +                    resolve(true);
Resolve only if `stats.isDirectory()`

2017-04-10 18:58 UTC, GiedriusGrabauskas commented on src/css-to-ts.ts
> +    private formTs(stringifiedCss: string, variableName: string, headerComment?: string) {
Rename `formTs`

2017-04-10 18:58 UTC, GiedriusGrabauskas commented on src/css-to-ts.ts
> +        if (headerComment) { tsContent += `// ${headerComment} \r\n`; }
Use `os.EOL`

2017-04-10 18:58 UTC, GiedriusGrabauskas commented on src/css-to-ts.ts
> +export class CssToTs {
Rename to `CssToTsConverter`

2017-04-10 18:58 UTC, GiedriusGrabauskas commented on src/css-to-ts.ts
> +    private formTs(stringifiedCss: string, variableName: string, headerComment?: string) {
Move to new file

2017-04-10 18:58 UTC, GiedriusGrabauskas commented on src/css-to-ts.ts
> +    private formTs(stringifiedCss: string, variableName: string, headerComment?: string) {
Use `CssToTs` name.

2017-04-10 22:11 UTC, DovydasNavickas requested changes

2017-04-10 22:11 UTC, DovydasNavickas commented on src/converter.ts
> +export class Converter {
Should be a more accurate name. E.g. `CssToTsConverter`

2017-04-10 22:11 UTC, DovydasNavickas commented on src/main.ts
> +    private kebabCaseToCamelCase(fileName: string) {
Consider changing `kebabCase` to `snakeCase` 🙂

2017-04-10 22:11 UTC, DovydasNavickas commented on src/css-to-ts.ts
> +export function CssToTs(stringifiedCss: string, variableName: string, headerComment?: string) {
Consider `ConvertCssToTs` function name

2017-04-10 22:11 UTC, DovydasNavickas commented on src/converter.ts
> +            const dirExists = await fs.stat(this.tsDir);
`dirExists` -> `dirStats`

2017-04-11 14:50 UTC, DeividasBakanas commented on package.json
> +}
Add `bin` for cli.

2017-04-11 14:50 UTC, DeividasBakanas commented on src/arguments.ts
> +        describe: "Specifies should the source CSS file should be removed"
Add `type: "string"`

2017-04-11 14:50 UTC, DeividasBakanas commented on src/arguments.ts
> +    .option("removeSource", {
Implement this option.

2017-04-12 14:34 UTC, GiedriusGrabauskas requested changes

2017-04-12 14:34 UTC, GiedriusGrabauskas commented on src/css-to-ts-converter.ts
> +        } catch (error) {
Check if error is null or undefined

2017-04-12 14:34 UTC, GiedriusGrabauskas commented on src/css-to-ts-converter.ts
> +        } catch (error) {
Or maybe use this function:
```ts
function IsNodeError(error: any): error is NodeJS.ErrnoException {
  return (exception != null && exception.errno != null);
}
```

2017-04-12 14:34 UTC, GiedriusGrabauskas commented on src/css-to-ts.ts
> +    if (headerComment) { tsContent += `// ${headerComment}${EOL}`; }
Add new line

2017-04-12 19:01 UTC, GiedriusGrabauskas requested changes

2017-04-12 19:01 UTC, GiedriusGrabauskas commented on src/helpers.ts
> +export const DEFAULT_IGNORED_GLOB = "node_modules/**/*.css";
Why this?

2017-04-12 19:06 UTC, DovydasNavickas requested changes

2017-04-12 19:06 UTC, DovydasNavickas commented on src/index.ts
> +export { Options, CSSToTsOptions } from "./contracts";
`CSSToTsOptions` is not consistent, because every other occurrence uses `Css` instead of `CSS`.

2017-04-12 19:06 UTC, DovydasNavickas commented on src/helpers.ts
> +export const DEFAULT_IGNORED_GLOB = "node_modules/**/*.css";
Because the default `rootDir` is `.` and the tool takes all CSS files in `node_modules`. It's updated a bit, thought, just not pushed yet.

2017-04-19 12:54 UTC, GiedriusGrabauskas requested changes

2017-04-19 12:54 UTC, GiedriusGrabauskas commented on package.json
> +    "package.json",
Remove package.json file

2017-04-19 18:20 UTC, DovydasNavickas approved these changes

2017-04-19 18:22 UTC, GiedriusGrabauskas approved these changes

2017-04-19 18:22 UTC, merged